apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: whoami-cas
  namespace: whoami
spec:
  plugin:
    cas-auth:
        casServerUrl: "https://keycloak.${CLUSTERNAME}.${DOMAINNAME}/realms/traefiklabs/protocol/cas"
        allowedHosts: 
          - "*.${CLUSTERNAME}.${DOMAINNAME}"
        pathPatterns: 
          - "/.*"
        sessionTimeout: 24h
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: whoami-oidc
  namespace: whoami
spec:
  plugin:
    oidc:
      issuer: "https://keycloak.${CLUSTERNAME}.${DOMAINNAME}/realms/traefiklabs"
      redirectUrl: "/cback"
      clientID: whoami-oidc
      clientSecret: bdfbDPx3ysnvzcNwzvJFWHMPKnHVn79c
      scopes:
        - openid
        - offline_access
      session:
        name: "%s-session"
      forwardHeaders:
        X-Traefik-User: preferred_username
        X-Traefik-Group: groups
