
image:
  registry: ghcr.io
  repository: traefik/traefik-hub
  tag: "v3"
deployment:
  replicas: 1
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  enabled: false
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true
    format: json
    addInternals: true
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: keep
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
        weight: 100
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 100m
ports:
  websecure:
    tls:
      enabled: true
      certResolver: le
additionalArguments:
  - '--certificatesresolvers.le.distributedAcme=true'
  - '--certificatesresolvers.le.distributedAcme.storage.kubernetes=true'
  - '--certificatesresolvers.le.distributedAcme.email=david.blaskow@traefik.io'
  - '--certificatesresolvers.le.distributedAcme.tlschallenge=true'
hub:
  token: hub-license
  apimanagement:
    enabled: false
