---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hub-dashboard
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`hub.${CLUSTERNAME}.${DOMAINNAME}`)
      services:
        - name: api@internal
          kind: TraefikService